
elasticsearch:
  build: elasticsearch
  volumes:
   - volumes/elasticsearch-data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"

logstash:
  build: logstash
  volumes:
    - volumes/logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch

kibana:
  build: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
